name: Build and Save

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build .

      - name: Build
        run: cmake --build build

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Program  # Имя архива, который вы скачаете
          path: build/MyProject
